### PR TITLE
Various CSS improvements

### PR DESCRIPTION
**Pull request by christian-bromann**
this patch includes:

- align the navigation links with our Next.js page (e.g. Documentation / Community / Blog / GitHub)
- remove unused CSS
- reverted https://github.com/stateful/docs.runme.dev/commit/5ed961f4763c1844a2c4a0171c307e61337c06c6 due to bug with layout (cc @sourishkrout), e.g.:
   layout-bug
- aligned size and positioning of Runme logo to make it appear similar to runme.dev

### CODE REVIEW

**Comment by sourishkrout** [comment]
Fair enough regarding the revert, @christian-bromann; any chance we can not have it take up 100% on a desktop screen and center it? Not sure if it's just me, but it looks 🫠 using up all the space horizontally.

I'm the first one to admit that CSS and I don't get along.

**Comment by sourishkrout** [comment]
Btw, it must be a Brave thing. Works fine in Chrome. Tested it when I committed it and it works now 🤷 .

**Comment by christian-bromann** [comment]
> any chance we can not have it take up 100% on a desktop screen and center it?

Sure thing! Let me push another fix for that.

**Comment by christian-bromann** [comment]
Screenshot 2023-05-23 at 16 03 38

**Pull request merged**
