### PR TITLE
chore(deps): Bump deps 20240815

### PR DESCRIPTION
**Pull request by sourishkrout**
@pastuxso, with the latest DocuSaurus, there is no space between the badge and the header. Do you have any idea how to fix this?

image

### CODE REVIEW

**Comment by pastuxso** [comment]
It's because the CSS selector does not match anymore. We need to adjust it.

New:

image

Old:

image


https://github.com/stateful/docs.runme.dev/pull/368/files#diff-44813f307e729042af7e70beff6f32ea63a7941bc100043a49e84d229ea2570fL293

Would you like me to fix it?

**Comment by sourishkrout** [comment]
> Would you like me to fix it?

Yes please

**Review by pastuxso — APPROVED** [review]
LGTM 🚀

**Comment by sourishkrout** [comment]
> LGTM 🚀

Gracias! 🙌

**Pull request merged**
