### PR TITLE
Reorganize the documentation journey

### PR DESCRIPTION
**Pull request by admc**
We had duplicated info in a number of places, it was hard to know the difference between a guide and an integration.

I've consolidated into this flow:
- Understand at a high level what runme is and why it exists
- Quickly find the thing you want to install
- Use the thing you installed
- Configure and expand
- All the peripheral info people might look for.

Guides become tutorials, which I have removed a bunch of unnecessary introduction, these need more work to make it clear why using them with runme adds value, like with Dagger.

### CODE REVIEW

**Comment by sourishkrout** [comment]
@admc are you on the latest version? Why do we have conflicts?

**Comment by admc** [comment]
@sourishkrout  Not sure what the deal was there, but I merged main, prob had to do with switching computers and pulling the branch without getting main first. But I think all the things are there and all links are fixed now.

**Comment by admc** [comment]
@sourishkrout okay, woke up with a bunch more changes in mind, I think I'm at a stopping point now if you wanna take a look 🙏

**Comment by sourishkrout** [comment]
What I'm noticing, unclear if they are showstoppers or not:
- [ ] The Getting Started content under `/getting-started/vscode` is really old - perhaps edit it down to what's relevant and put the Quickstart guide at the top?
- [ ] Badges are gone, i.e. no more Runme frontmatter in the docs. This is okay, if the document itself is not runnable.
- [ ] Cutover will break links. We should make sure we have redirects in place.

**Comment by admc** [comment]
Just checked in an updated vercel.json based on sitemap diff.

**Review by sourishkrout — APPROVED** [review]
✅ LGTM

**Pull request merged**
